FROM ghcr.io/raw-labs/raw-fdw:0.8.5_pg15_gvm21.0.0

RUN apt install libprotobuf-dev protobuf-compiler libgrpc++-dev \
    pkg-config protobuf-compiler-grpc libselinux1-dev libzstd-dev \
    liblz4-dev libpam0g-dev libkrb5-dev libc++-dev libc++abi-dev -y